CREATE TABLE Users
(
    userId VARCHAR(100) PRIMARY KEY,
    Name VARCHAR(200) ,
    Email VARCHAR(300) UNIQUE,
    Password VARCHAR(150),
    Role VARCHAR(100) DEFAULT 'user',
    isActive BIT NOT NULL DEFAULT 0,
    isSent VARCHAR(150) DEFAULT '0',
    createdAt DATETIME NOT NULL DEFAULT GETDATE()
)
